### ISSUE TITLE
upgrades/jade-backbone issues

### ISSUE THREAD

**Issue by orlin** [node-organic/organic-stem-skeleton#1]
I found some issues with the results of running `node ./node_modules/.bin/angel stack add upgrades/jade-backbone`:
- `.gitignore` overwritten (append is expected, also parse to avoid adding duplicates?)
- `package.json`'s `jade` downgraded to `1.3.1` from `^1.6.0` - intentional?
- `node_modules` is better than `/node_modules` (one may have package.json with its node_modules in sub-directories, e.g. of a node-webkit app that is part of the same project)
- global `bower` is assumed, even though a dependency - how about: `"install": "./node_modules/.bin/bower install"` (in package.json)?

**Comment by outbounder** [comment]
@orlin latest upstream code base has the above mentioned suggestions implemented ;)
